# Generated by Django 4.1.7 on 2023-05-05 17:21

from django.db import migrations, models
import django.db.models.deletion
import main.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Wedding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='название')),
            ],
            options={
                'verbose_name': 'Свадьба',
                'verbose_name_plural': 'Свадьба',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='WeddingPhotos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photos', models.ImageField(upload_to=main.models.upload_photos, verbose_name='фото')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wedding_photos', to='main.wedding')),
            ],
            options={
                'verbose_name': 'Фото',
                'verbose_name_plural': 'Все фото',
            },
        ),
    ]
